name: Update repo to match @chainlink/contracts

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  jobs:
    job-public-repo:
      runs-on: ubuntu-latest
      steps:
        # - name: Clone https://github.com/smartcontractkit/chainlink
        #   uses: GuillaumeFalourd/clone-github-repo-action@main
        #   with:
        #     owner: 'smartcontractkit'
        #     repository: 'chainlink'

        # - name: Compare contracts folder
        #   run: |
        #     cd contracts
        #     ls -l
        - name: Check @chainlink/contracts
          uses: EndBug/version-check@v1
        - name: Update package
          if: steps.check.outputs.changed == 'true'
          run: echo "test"
